- name: Play find reable hosts
  hosts: device_roles_host
  become: True
  become_user: root
  gather_facts: False
  tasks:
    - name: Run a block
      block:
        - name: Determine if host is reachable
          wait_for_connection:
            timeout: 10
          ignore_unreachable: True
          ignore_errors: True
        - name: Create host group for reachable host
          group_by:
            key: up_hosts

- name: Output all up systems
  hosts: up_hosts
  become: True
  become_user: root
  gather_facts: False
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated and not in group tags_noreboot
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: "reboot_required_file.stat.exists and 'tags_noreboot' not in group_names"
